name: practical-ai
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6
  - argparse=1.4.0
  - django=2.1.3
  - gensim=3.6.0
  - image=1.5.27
  - jsonschema=2.6.0
  - matplotlib=2.1.2
  - numpy=1.14.6
  - pandas=0.22.0
  - Pillow=4.0.0
  - regex=2017.11.9
  - requests=2.18.4
  - scikit-learn=0.19.2
  - tensorboardX=1.4
  - tensorflow=1.12.0
  - torch=0.4.1
  - torchvision=0.2.1
  - ujson=1.35
  - urllib3==1.22